[dependencies]
base = "0.14.1"
http-types = "1.0.1"
openchat-bot-sdk = "https://github.com/edjCase/motoko_oc_bot_sdk#master@608a77faedfc5d9147e7d329b62697a137d979ca"
base64 = "1.0.0"
xtended-numbers = "0.3.1"
itertools = "0.2.2"
json = "1.0.1"
ecdsa = "0.0.2"
