[dependencies]
base = "0.14.3"
http-types = "1.0.1"
openchat-bot-sdk = "0.0.7"
base64 = "1.0.0"
xtended-numbers = "0.3.1"
itertools = "0.2.2"
json = "1.0.1"
ecdsa = "1.0.0"
sha2 = "0.1.0"
stableheapbtreemap = "1.5.0"
star = "0.1.1"
map = "9.0.1"
vector = "0.4.1"
candy = "0.3.0"
icrc1-mo = "0.0.15"
ovs-fixed = "0.1.2"
candy-utils = "0.7.0"
ic-certification = "0.1.3"
base16 = "1.0.0"
account = "1.0.1"
account-identifier = "1.0.2"
icrc72-subscriber-mo = "0.0.1"
